version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 2
      SOURCE_URL: https://etherscan.io/txsPending
      # SOURCE_URL: wss://mainnet.infura.io/ws/a699fa2391894c5799607f10f8b89ab3
  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_TOPIC: streaming.transactions

  generator_block:
    build: ./generator_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      # KAFKA_LOG4J_LOGGERS : kafka.controller=WARN, kafka.foo.bar=DEBUG  
      # KAFKA_LOG4J_ROOT_LOGLEVEL : WARN 
      # KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR 
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 1
      NUMBER_OF_CONFIRMATIONS: 12
      SOURCE_URL: wss://mainnet.infura.io/ws

  detector_block:
    build: ./detector_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_TOPIC: streaming.transactions
      # TRANSACTIONS_BLOCKTIME_TOPIC: streaming.blocktime.transactions
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      SOURCE_BLOCKDETAILS_URL: wss://mainnet.infura.io/ws/a699fa2391894c5799607f10f8b89ab3

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: transactions3
    volumes:
      - ./data/db:/data/db

  detector_summary:
    build: ./detector_summary
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: streaming.transactions
      TRANSACTIONS_SUMMARY_TOPIC: queueing.summary.transactions
      MONGO_INITDB_DATABASE: transactions3
    depends_on:
      - mongodb

  receiver_summary:
    build: ./receiver_summary
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_SUMMARY_TOPIC: queueing.summary.transactions
      MONGO_INITDB_DATABASE: transactions3
      # URL: https://etherscan.io/tx/
      URL: wss://mainnet.infura.io/ws/a699fa2391894c5799607f10f8b89ab3
      BATCH_INTERVAL: 1
    depends_on:
      - mongodb

  receiver_block_time:
    build: ./receiver_block_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      MONGO_INITDB_DATABASE: transactions3
      NUMBER_OF_CONFIRMATIONS: 12
      BATCH_INTERVAL: 1
    depends_on:
      - mongodb      
  web:
    build: ./web
    environment: 
      BATCH_INTERVAL: 10
      MONGO_INITDB_DATABASE: transactions3
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    volumes:
      - ./test/:/data/test

networks:
  default:
    external:
      name: kafka-network
