version: '3'

services:

  generator_block:
    build: ./generator_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 1
      NUMBER_OF_CONFIRMATIONS: 12
      SOURCE_URL: wss://mainnet.infura.io/ws

  detector_block:
    build: ./detector_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_TOPIC: streaming.transactions
      # TRANSACTIONS_BLOCKTIME_TOPIC: streaming.blocktime.transactions
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      SOURCE_BLOCKDETAILS_URL: wss://mainnet.infura.io/ws/a699fa2391894c5799607f10f8b89ab3
      NUMBER_OF_CONFIRMATIONS: 12

  receiver_block_time:
    build: ./receiver_block_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      NUMBER_OF_CONFIRMATIONS: 12
      BATCH_INTERVAL: 1
      
networks:
  default:
    external:
      name: kafka-network
