version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 1

  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_TOPIC: streaming.transactions
  
  detector_transaction_detail:
    build: ./detector_transaction_detail
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: streaming.transactions
      TRANSACTIONS_DETAILS_TOPIC: streaming.transactions.details
      DATASOURCE: 'https://etherscan.io/tx/'

  receiver_start_time:
    build: ./receiver_start_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_TOPIC: streaming.transactions
  
  Mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: transactions
      
networks:
  default:
    external:
      name: kafka-network
