version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 2
      SOURCE_URL: wss://mainnet.infura.io/ws

  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_TOPIC: streaming.transactions
  
  # detector_transaction_detail:
  #   build: ./detector_transaction_detail
  #   environment:
  #     KAFKA_BROKER_URL: broker:9092
  #     TRANSACTIONS_TOPIC: streaming.transactions
  #     TRANSACTIONS_DETAILS_TOPIC: streaming.transactions.details
  #     DATASOURCE: 'https://etherscan.io/tx/'

  generator_block:
    build: ./generator_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 5
      SOURCE_URL: wss://mainnet.infura.io/ws

  detector_block:
    build: ./detector_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_BLOCKTIME_TOPIC: streaming.transactions.blocktime
      SOURCE_BLOCKDETAILS_URL: wss://mainnet.infura.io/ws/4a6762bdc2e34b08b84a3b14f337093b

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: transactions


  receiver_start_time:
    build: ./receiver_start_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_TOPIC: streaming.transactions
      MONGO_INITDB_DATABASE: transactions
    depends_on:
      - mongodb
    
  receiver_end_time:
    build: ./receiver_end_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCKTIME_TOPIC: streaming.transactions.blocktime
      MONGO_INITDB_DATABASE: transactions
    depends_on:
      - mongodb
      
networks:
  default:
    external:
      name: kafka-network
