version: '3'

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: transactions


  receiver_start_time:
    build: ./receiver_start_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_TOPIC: streaming.transactions
    depends_on:
      - mongodb
      
networks:
  default:
    external:
      name: kafka-network
