version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 5
      SOURCE_URL: wss://mainnet.infura.io/ws

  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_TRANSACTIONS_TOPIC: queueing.raw.transactions
      TRANSACTIONS_TOPIC: streaming.transactions
  
  # detector_transaction_detail:
  #   build: ./detector_transaction_detail
  #   environment:
  #     KAFKA_BROKER_URL: broker:9092
  #     TRANSACTIONS_TOPIC: streaming.transactions
  #     TRANSACTIONS_DETAILS_TOPIC: streaming.transactions.details
  #     DATASOURCE: 'https://etherscan.io/tx/'

  generator_block:
    build: ./generator_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      KAFKA_LOG4J_LOGGERS : kafka.controller=WARN, kafka.foo.bar=DEBUG  
      KAFKA_LOG4J_ROOT_LOGLEVEL : WARN 
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR 
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      TRANSACTIONS_PER_SECOND: 1000
      REQUEST_INTERVAL: 10
      SOURCE_URL: wss://mainnet.infura.io/ws

  detector_block:
    build: ./detector_block
    environment:
      KAFKA_BROKER_URL: broker:9092
      RAW_BLOCKS_TOPIC: queueing.raw.blocks
      # TRANSACTIONS_TOPIC: streaming.transactions
      TRANSACTIONS_BLOCKTIME_TOPIC: streaming.blocktime.transactions
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      SOURCE_BLOCKDETAILS_URL: wss://mainnet.infura.io/ws/4a6762bdc2e34b08b84a3b14f337093b

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: transactions
    volumes:
      - ./data/db:/data/db

  receiver_start_time:
    build: ./receiver_start_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_TOPIC: streaming.transactions
      MONGO_INITDB_DATABASE: transactions
      URL: https://etherscan.io/tx/
      BATCH_INTERVAL: 2
    depends_on:
      - mongodb

  receiver_start_time_2:
    build: ./receiver_start_time_2
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_TOPIC: streaming.transactions
      MONGO_INITDB_DATABASE: transactions
      URL: https://etherscan.io/tx/
      BATCH_INTERVAL: 2
    depends_on:
      - mongodb  

  receiver_end_time:
    build: ./receiver_end_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCKTIME_TOPIC: streaming.blocktime.transactions
      MONGO_INITDB_DATABASE: transactions
      URL: https://etherscan.io/tx/
      BATCH_INTERVAL: 2      
    depends_on:
      - mongodb

  receiver_end_time_2:
    build: ./receiver_end_time_2
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCKTIME_TOPIC: streaming.blocktime.transactions
      MONGO_INITDB_DATABASE: transactions
      URL: https://etherscan.io/tx/
      BATCH_INTERVAL: 2      
    depends_on:
      - mongodb

  receiver_block_time:
    build: ./receiver_block_time
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      MONGO_INITDB_DATABASE: transactions
      NUMBER_OF_CONFIRMATIONS: 12
      BATCH_INTERVAL: 20   
    depends_on:
      - mongodb    

  receiver_block_time_2:
    build: ./receiver_block_time_2
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TRANSACTIONS_BLOCK_TOPIC: queueing.blocktime.blocks
      MONGO_INITDB_DATABASE: transactions
      NUMBER_OF_CONFIRMATIONS: 12
      BATCH_INTERVAL: 20   
    depends_on:
      - mongodb   

networks:
  default:
    external:
      name: kafka-network
